package ryleh.model;
public enum Type {
	PLAYER, BOSS, ROCK, DOOR, ENEMY_DRUNK,ENEMY_SHOOTER, ITEM, BACKGROUND, 
  PLAYER_BULLET, ENEMY_BULLET,ENEMY_LURKER,ENEMY_SPINNER,ENEMY_DRUNKSPINNER, WALL, FIRE;
}
